<?php

namespace AppBundle\Repository;

/**
 * PhoneTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
