AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: last_name
        lastName:
            type: string
            length: 255
            column: first_name
        number:
            type: string
            length: '50'
        phoneTypeId:
            type: integer
            column: phone_type_id

    manyToOne:
        phoneType:
            targetEntity: PhoneType
            joinColumn:
                name: phone_type_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
