AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastName:
            type: string
            length: 255
            column: last_name
        firstName:
            type: string
            length: 255
            column: first_name
        number:
            type: string
            length: 50
        phoneTypeId:
            type: integer
            column: phone_type_id
    manyToOne:
        phone_type:
            targetEntity: PhoneType
            inversedBy: contacts
            joinColumn:
                name: phone_type_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
