AppBundle\Entity\PhoneNumber:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PhoneNumberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: string
            length: '50'
        contactId:
            type: integer
            column: contact_id
        phoneTypeId:
            type: integer
            column: phone_type_id

    manyToOne:
        contact:
            targetEntity: Contact
            inversedBy: phoneNumbers
            joinColumn:
                name: contact_id
                referencedColumnName: id
        phone_type:
            targetEntity: PhoneType
            joinColumn:
                name: phone_type_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
